name                            : randla_erda

activation                      : lrelu
architecture                    : [
        unary,
        __input__,
        resnetb-lfa,
        pool-max,
        resnetb-lfa,
        pool-max,
        resnetb-lfa,
        pool-max,
        resnetb-lfa,
        pool-max,
        resnetb-lfa,
        pool-max,
        unary,
        upsample-nst_concat_2,
        upsample-nst_concat_2,
        upsample-nst_concat_2,
        upsample-nst_concat_2,
        upsample-nst_concat_2,
        __output__,
        mlp-1-xen-dp.5-class,
        pseudo-fout-pmlp2-mom-Gsum-normdot-w.1,
]
architecture_dims               : [64, 128, 256, 512, 1024, 2048]
augment_noise                   : 0.001
augment_rgb_contrast            : ''
augment_rgb_drop                : 0.8
augment_rgb_hstrans             : ''
augment_rgb_noise               : ''
augment_rgb_trans               : ''
augment_rotation                : vertical
augment_scale_anisotropic       : True
augment_scale_max               : 1.3
augment_scale_min               : 0.7
augment_symmetries              : [True, False, False]
batch_size                      : 6
batch_size_val                  : 16
bn_eps                          : 1.e-06
bn_momentum                     : 0.99
bottleneck_ratio                : 4
colocate_gradients_with_ops     : False
conv                            : lfa
cpu_variables                   : False
data_path                       : Data
dataset                         : S3DIS
decay                           : ''
decay_epoch                     : 1
decay_rate                      : 0.9885530946569389
density_parameter               : 5.0
depth                           : 1
distribute                      : tf_device
drop                            : dp.5
epoch_batch                     : 12
epoch_steps                     : 500
first_features_dim              : 32
first_subsampling_dl            : 0.04
grad_norm                       : 100
grad_raise_none                 : True
in_features                     : 1rgbxyzZ
in_features_dim                 : 5
in_points                       : 40960
in_radius                       : 2.0
info_gen                        : ''
init                            : xavier
join                            : concat_2
kr_sample                       : [16, 16, 16, 16, 16]
kr_sample_up                    : [1, 1, 1, 1, 1]
kr_search                       : [16, 16, 16, 16, 16, 16]
lazy_inputs                     : False
learning_rate                   : 0.01
loss_weight                     : 
max_epoch                       : 200
max_to_keep                     : 15
mode                            : train-val
momentum                        : 0.98
neighborhood_limits             : [26, 31, 38, 41, 39, 29]
noise_init                      : 3.5
num_classes                     : 13
num_layers                      : 6
num_threads                     : 12
num_votes                       : 20
optimizer                       : adam
print_freq                      : 60
r_sample                        : [4, 4, 4, 4, 2]
rand_seed                       : 0
repeat                          : 1
runtime_freq                    : 0
sample                          : random
save_best                       : True
save_compact                    : True
save_freq                       : 0
save_sample                     : False
save_test                       : False
saving                          : True
search                          : knn
snap_dir                        : snapshots
snap_prefix                     : snap
summary                         : False
up                              : nst
update_freq                     : 10
val_freq                        : 1
validation_steps                : 100
version                         : aligned
weight_decay                    : 0
